name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'
          cache: true

      - name: Ensure go.mod exists (init if missing)
        run: |
          if [ ! -f go.mod ]; then
            echo "No go.mod found; initializing a temporary one for CI."
            go mod init example.com/device-info
          fi
          go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
